#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-activesupport
Version  : 4.2.3
Release  : 8
URL      : https://rubygems.org/downloads/activesupport-4.2.3.gem
Source0  : https://rubygems.org/downloads/activesupport-4.2.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
= Active Support -- Utility classes and Ruby extensions from Rails
Active Support is a collection of utility classes and standard library
extensions that were found useful for the Rails framework. These additions
reside in this package so they can be loaded as needed in Ruby projects
outside of Rails.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n activesupport-4.2.3
gem spec %{SOURCE0} -l --ruby > rubygem-activesupport.gemspec

%build
gem build rubygem-activesupport.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
activesupport-4.2.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/activesupport-4.2.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/all.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/backtrace_cleaner.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/benchmarkable.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/cache.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/cache/file_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/cache/mem_cache_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/cache/memory_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/cache/null_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/concern.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/concurrency/latch.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/configurable.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/array/access.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/array/conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/array/extract_options.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/array/grouping.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/array/prepend_and_append.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/array/wrap.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/big_decimal.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/big_decimal/conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/big_decimal/yaml_conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/class.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/class/attribute.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/class/attribute_accessors.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/class/delegating_attributes.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/class/subclasses.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date/acts_like.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date/calculations.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date/conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date/zones.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date_and_time/calculations.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date_and_time/zones.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date_time.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date_time/acts_like.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date_time/calculations.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date_time/conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/date_time/zones.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/digest/uuid.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/enumerable.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/file.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/file/atomic.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/compact.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/deep_merge.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/except.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/indifferent_access.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/keys.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/reverse_merge.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/slice.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/transform_values.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/integer.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/integer/inflections.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/integer/multiple.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/integer/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/kernel.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/kernel/agnostics.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/kernel/concern.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/kernel/debugger.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/kernel/reporting.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/kernel/singleton_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/load_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/marshal.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/aliasing.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/anonymous.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/attr_internal.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/attribute_accessors.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/concerning.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/delegation.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/deprecation.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/introspection.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/method_transplanting.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/qualified_const.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/reachable.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/module/remove_method.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/name_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/numeric.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/numeric/bytes.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/numeric/conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/numeric/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/acts_like.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/blank.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/deep_dup.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/duplicable.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/inclusion.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/instance_variables.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/itself.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/to_param.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/to_query.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/try.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/object/with_options.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/range.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/range/conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/range/each.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/range/include_range.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/range/overlaps.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/regexp.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/access.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/behavior.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/exclude.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/filters.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/indent.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/inflections.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/inquiry.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/multibyte.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/output_safety.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/starts_ends_with.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/strip.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/string/zones.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/struct.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/thread.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/time/acts_like.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/time/calculations.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/time/conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/time/marshal.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/time/zones.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/uri.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies/autoload.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/deprecation.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/deprecation/behaviors.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/deprecation/instance_delegator.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/deprecation/method_wrappers.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/deprecation/proxy_wrappers.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/deprecation/reporting.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/descendants_tracker.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/duration.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/file_update_checker.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/gem_version.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/gzip.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/hash_with_indifferent_access.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/i18n.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/i18n_railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/inflections.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/inflector.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/inflector/inflections.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/inflector/methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/inflector/transliterate.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/json/decoding.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/json/encoding.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/key_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/locale/en.yml
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/log_subscriber.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/log_subscriber/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/logger_silence.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/message_encryptor.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/message_verifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/multibyte.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/multibyte/chars.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/multibyte/unicode.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/notifications/fanout.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/number_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/number_helper/number_converter.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/number_helper/number_to_currency_converter.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/number_helper/number_to_delimited_converter.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/number_helper/number_to_human_converter.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/number_helper/number_to_human_size_converter.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/number_helper/number_to_percentage_converter.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/number_helper/number_to_phone_converter.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/number_helper/number_to_rounded_converter.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/option_merger.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/ordered_hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/ordered_options.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/per_thread_registry.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/proxy_object.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/rescuable.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/security_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/string_inquirer.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/subscriber.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/test_case.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/testing/assertions.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/testing/autorun.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/testing/constant_lookup.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/testing/declarative.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/testing/deprecation.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/testing/isolation.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/testing/setup_and_teardown.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/testing/tagged_logging.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/testing/time_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/time_with_zone.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/values/time_zone.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/values/unicode_tables.dat
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/xml_mini.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/xml_mini/jdom.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/xml_mini/libxml.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/xml_mini/libxmlsax.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/xml_mini/nokogiri.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/xml_mini/nokogirisax.rb
/usr/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/xml_mini/rexml.rb
/usr/lib64/ruby/gems/2.3.0/specifications/activesupport-4.2.3.gemspec
